requirements_task:
  description: >
      You are an expert Scrum Business Analyst.  Your mission is to analyse all product\'s elements in the vision file and Identify the needs and expectations of the stakeholders and Write a professional report of all the product requirements using the tool.
      Detail each requirements and validate the conclusion with the stackholder.
      the requirement file should be a text file.
      the text file should containing just the content of the product vision and the requirement list.
  expected_output: >
    text file 'requirements.txt' containing the requirements of a Scrum Product.
  agent: requirements

Jira_research_task:
  description: >
      You are an Atlassian and JIRA expert.  After that the requirements agent finished. Your mission is to to generate CSV/Excel template that matches the structure of Jira backlog items, including the most common fields
      used for Epics, User Stories, Tasks, Bugs, and Sub-tasks.add two columns for prioritizing  and estimating effort for all backlog items
      Detail the standard elements expected in each backlog item and the associated fields Then save them to a CSV file using the tool. 
      make sure: The headers match Jira's expected columns (Issue Type,Issue ID, Summary, Description, etc.), You use CSV UTF-8 format, Multi-line values (like in “Acceptance Criteria”) are quoted properly, The Epic Name and Link system matches your Jira config.
      the same file should containing Epics, user stories, Tasks ans sub-tasks with their details
  expected_output: >
    CSV file 'backlog.csv' containing structure of a Scrum Product Backlog.
  agent: Jira_research

Epics_task:
  description: >
    You are a Scrum expert. Based on this product description and according to the structure of Jira_research's backlog structure,
    Generate all Epics for the product.
     Then Saves the output to the backlog.csv file using a custom tool or Python logic"
  expected_output: >
    CSV file 'backlog.csv' containing epics.
  agent: Epics

User_Stories_task:
  description: >
    You are a Scrum expert. Based on this product description and according to the Epics's backlog content,
    Generate all user stories for the product.
     Then adds the output to the backlog.csv file using a custom tool or Python logic"
  expected_output: >
    CSV file 'backlog.csv' containing epics and user stories.
  agent: User_Stories


Tasks_task:
  description: >
    You are a Scrum expert. Based on this product description and according to the User_Stories's backlog content,
    Generate all tasks and sub-tasks for the product.
     Then adds the output to the backlog.csv file using a custom tool or Python logic"
  expected_output: >
    CSV file 'backlog.csv' containing epics, user stories, tasks and sub-tasks.
  agent: Tasks